SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((C.DAILY_FEE * 30) * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND C.CAR_ID NOT IN (
      SELECT H.CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      WHERE (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
  )
  AND (C.DAILY_FEE * 30) * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
