-- 코드를 입력하세요
SELECT FLAVOR 
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS S
    FROM (SELECT FLAVOR, TOTAL_ORDER FROM JULY AS J 
          UNION ALL 
          SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF AS F) AS COMBINED
 GROUP BY FLAVOR) AS RESULT
ORDER BY S DESC LIMIT 3;